// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atqgxbtersrdkjufszyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cWd4YnRlcnNyZGtqdWZzenl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDc0NjYsImV4cCI6MjA1MzIyMzQ2Nn0.sY6TdSV-o6uZiMlWrltuaYRafS7F2nVFO-vR4y9022k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);